spring.application.name=ChatBot_Service

server.port=8082

eureka.client.service-url.defaultZone=https://serviceregistry-9y5o.onrender.com/eureka

spring.datasource.url=jdbc:postgresql://dpg-d6p4h2h5pdvs739resu0-a.singapore-postgres.render.com:5432/zest_vendorapp_pg
spring.datasource.username=zest_vendorapp_pg_user
spring.datasource.password=pSyzBuQ9aYualFSkbwQOGcnD9LY4aeKL

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.config.enabled=false

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

#springdoc.packages-to-scan=com.chatbot
springdoc.show-actuator=false

jwt.secret=chatbot-super-secret-key-minimum-32-characters-long
jwt.expiry=86400000
